### ISSUE TITLE
Documentation request?

### ISSUE THREAD

**Issue by nsmsn** [janboddez/indieblocks#123]
Would you consider adding a "Gallery" page, or examples of sites that use the Indieblocks plugin? Such a page should be opt-in, but I'm interested in finding/following other WP users building their sites with Indieblocks.

**Comment by janboddez** [comment]
Ha, good idea!

Meanwhile, I know of (linking to the pages/sections that most clearly show IndieBlocks' presence):

https://jan.boddez.net/notes (mine, obviously)
https://ochtendgrijs.be/notes/ (mine also)
https://indieblocks.xyz/stream/ (also mine, not the best example)
https://cagrimmett.com/micro/ (_not_ mine, finally 😄)

Now, there almost _have_ to be at least a few more, but I clearly don't know of them.

Also, there's quite a few ways you can use the plugin, so it may not very obvious the it is even active.

Like, you can choose to not use the blocks, or the post types. Or only use the post types, or not have the plugin automatically generate (certain) post titles, and so on. Or use it only to add microformats to block themes! That said, that, too, would be kind of interesting to see!

**Comment by janboddez** [comment]
Also, those first two sites are, in fact, part of the same WordPress Multisite install. Use the same base theme, even. And (I know it's silly, but) I was considering to open that up to other sites/users, so as to start a stripped down (like, a lot) "WordPress version of micro.blog."

**Comment by nsmsn** [comment]
Thanks for providing the links. And I'll share mine (once I get up and running) if you are collecting them. 

Is the base theme something you have open sourced? I am playing around with the [fullsiteediting.com theme generator](https://fullsiteediting.com/block-theme-generator/) plus the create-block-theme plugin.

**Comment by janboddez** [comment]
I use [this theme](https://github.com/janboddez/indielol). Started off as a heavily stripped down Twenty Twenty-Three. Added a couple templates to support IndieBlocks' post types. Switched out fonts for way smaller files. And so on, and so on. ("Indie.lol" is where I host my multisite install, in case anyone wonders about the name ...)

**Comment by nsmsn** [comment]
If you'd like to add another site using the plugin, check out [https://nicksimson.com/notes](https://nicksimson.com/notes/) and [https://nicksimson.com/likes](https://nicksimson.com/likes/).

**Comment by janboddez** [comment]
Cool!

Purely FYI: I noticed you're not using, e.g., the Like block, which is a perfectly valid choice (of course), but it does cause your likes to miss a `u-like-of` class, which ... is what makes them likes, as far as microformats parsers are concerned.

See also:
https://xray.p3k.app/parse?url=https%3A%2F%2Fnicksimson.com%2Flikes%2F258-2%2F&pretty=true
https://pin13.net/mf2/?url=https%3A%2F%2Fnicksimson.com%2Flikes%2F258-2%2F

And:
https://indieweb.org/like#mark_up_and_post_a_like

(I mean, unless this is an import from an older post or something.)

Now, how important is this? It isn't, not really. Unless you're also sending webmentions and want the _other_ site (the one whose page you liked) to know that your like is, well, a _like_ and not a "regular" mention. 8-) (They're still free to treat it however they please, so no need to overthink it _too much_.)

The same holds for (notes that are also) bookmarks, replies, reposts, and such. The different blocks generate not just the necessary markup, they are also able to hold "inner blocks" which then get wrapped in a `div.e-content` or similar.

(How's that important? Again, it isn't, but microformats can be nested, and so on. Some "social readers" use this to their advantage. I believe Aperture/Monocle shows the original author's name, if it is correctly marked up, for reposts. On the other hand, only a handful people seem to actually use such readers. Plus, it takes a bit of HTML knowledge _and_ some tweaking to get 100% right, unfortunately.)

**Comment by nsmsn** [comment]
Thanks. The older likes in there now were posts from micro.blog, which
probably doesn’t include the proper markup for an IndieWeb like. I should
go back and eventually update them all to use the proper block. Thanks
again for bringing this to my attention.
