### ISSUE TITLE
Canonical URLs for Brid.gy replies (facepile)

### ISSUE THREAD

**Issue by nsmsn** [janboddez/indieblocks#133]
I'm running both the Webmention plugin and Indieblocks, and set up my site with Brid.gy to bring in social media responses as webmentions. I'm using the facepile block in my block theme templates.

A few people in the Indieweb community chat noticed that the facepile "likes" are pointed to brid.gy links instead of the canonical URL. https://chat.indieweb.org/wordpress/2023-11-07#bottom

This post is a good example: https://nicksimson.com/likes/1e88a68f6a/

The brid.gy links in the facepile do redirect to the source (in this case my post on mastodon.design). The comments/replies below the facepile (also on mastodon, brought in by Brid.gy) link to their canonical source, which I *think* is the Webmention plugin at work. Apparently the Webmentions plugin uses the canonical URL automatically for replies brought in from Brid.gy.

Curious to hear your thoughts.

**Comment by janboddez** [comment]
Ah, good call. I get them from `get_comment_meta( $comment->comment_ID, 'webmention_source_url', true )` but the plugin might store the "real" URLs elsewhere.

Edit: Actually, they provide a function for this ... Using that would probably be more robust but break if you were to ever disable the Webmention plugin; think I'll just grab it from the "correct" field instead.

**Comment by janboddez** [comment]
Ah, there you go, it uses the (somewhat generic?) `url` field. (https://github.com/pfefferle/wordpress-webmention/blob/c2670adeef6cba4fe3676640a8a94bd24492ce63/includes/functions.php#L200) I'll update that in the next version.

**Comment by nsmsn** [comment]
Thanks for looking into it.

**Comment by janboddez** [comment]
Should be fixed in v0.9.1 (https://github.com/janboddez/indieblocks/blob/ebdd9052ac491e9c9f119e9717008a12553422df/blocks/facepile-content/class-facepile-content-block.php#L79C29-L79C29).

**Comment by janboddez** [comment]
In fact it now looks okay on the mentioned page :-D
