### ISSUE TITLE
Bookmarklets?

### ISSUE THREAD

**Issue by janboddez** [janboddez/indieblocks#142]
So, I never really felt the need for bookmarklets anymore, as:

1. on mobile there's a few decent Micropub clients, and this plugin supports Micropub and (if applicable) will even attempt to convert your Micropub content to blocks, and set the correct post type; and
2. on the desktop, we can just use WP Admin, copy-and-paste a URL and (possibly) some of the liked/bookmarked/replied-to page's content, etc.

However, it _could_ be nice to have some sort of bookmarklet functionality, so that we can just select some text on a page, click the bookmark (or so) bookmarklet, hit "Publish."

Side note: one could also set up some "starter patterns," like, have a bookmark block already present for the "bookmark" pattern, etc. (Currently, only likes come with a "preinstalled" Like block, because a note can be different "post kinds" [including a like, even, haha].)

**Comment by janboddez** [comment]
It _probably is_ possible to work off the existing Press This plugin/bookmarklet, although it'll likely need modified (a bit).

Like, on the JS side, might have to add a post type (manually, once for each [type of] bookmarklet).

Because the default interface does not support a post type field (yet). And I don't think it's filterable either. Although there is a button to switch to the "regular" editor, where, if you have a post type switcher plugin installed, you _could_ select a post type. Only thing is it breaks IndieBlocks' automatic slug function.

And then on the server side we can have a filter callback pick this up.

And, additionally, have the submitted content set as a certain "Indie" block's InnerBlocks, for instance.

**Comment by janboddez** [comment]
Alternatively, it might be possible to just do, you know, https://example.org/wp-admin/post-new.php?post_type=indieblocks_like&url=http://example.net or something, and have the block code pick up that URL. Not sure if we want that, though? I mean, I don't think it's any different, really, from those "Share on Twitter" and so on links?

That wouldn't be too different from copy-and-pasting the URL, although it would save you a few clicks. You'd lose the possibility to select text and whatnot, though. Compared to "Press This," I mean.

**Comment by cagrimmett** [comment]
I also use Micropub on mobile. Since I'm on iOS, I made shortcuts to post with Micropub: https://cagrimmett.com/development/2023/02/12/ios-shortcut-actions-for-micropub-posting/

The main reason I asked about this [on Mastodon](https://toot.cafe/@cagrimmett/111486453630276415) in the first place is that I was hoping to reduce the few clicks on desktop :) What I had in mind was something like `&url=https://example.com` on the end of the URL (though in this particular example &url is used for the Embed block) and maybe a &quote to pass highlighted text to an innerblock. In this case it would open up a browser tab with the url and highlighted content pre-filled so I can edit and press publish. I briefly glanced over the block code and didn't see anything, so I thought I'd ask. 

It isn't a blocker in any way, as there are options, just a nice to have. Thanks for your consideration!

**Comment by janboddez** [comment]
(Don't mind me, just going through some old issues here ...)

So, one reason I didn't pick this up (other than not _really_ needing it myself 😬) is me typically being overly paranoid about "CSRF attacks" and the like.

---

Like, adding a URL to a IndieBlocks block will typically, or eventually, fire off a server-side fetch of the resource at that URL. Which may very well be harmless. [We do limit response sizes, for instance.]

Or you could be adding, I don't know, invisible text or something to your post. Like, if someone sent you a link that'd send you to the Create Post screen with some params pre-filled. [Although we should probably strip all HTML tags and whatnot.]

And, even though you'd still need to press Publish, a draft of the post may get saved without user interaction.

I'm guessing the bookmarklet would pick up the current URL + `window.getSelection()` or something, and then tack those onto, e.g., `https://example.org/wp-admin/post-new.php?post_type=indieblocks_note` and forward the user to that page?

---

Note to self: looks like `wp.data.dispatch('core/editor').insertBlocks()` may allow us to inject a block into the editor. So we could look for a certain URL parameter, set up a block if it's there, then inject it into the editor.

**Comment by janboddez** [comment]
> Note to self: looks like `wp.data.dispatch('core/editor').insertBlocks()` may allow us to inject a block into the editor. So we could look for a certain URL parameter, set up a block if it's there, then inject it into the editor.

Ha, so we could potentially have something like `https://example.org/wp-admin/post-new.php?post_type=indieblocks_note&kind=bookmark` and at least add an (empty) bookmark block. (Or maybe we should pick a different name for the arg, to not interfere with Post Kinds.)

Not quite there, but it'd save a couple clicks. (Wouldn't have to select either a block pattern nor click in the editor and type `/boo` or something until the block can be selected.)

**Comment by janboddez** [comment]
Very first attempt: https://github.com/janboddez/indieblocks/commit/1b97c53d4865ee8dc76bf9e8b1b2dbcf81745bc8.

There's no actual bookmarklets here, but basically, if you navigate to your site's, e.g., `wp-admin/post-new.php?post_type=indieblocks_note&indieblocks_bookmark=https%3A%2F%2Fgithub.com%2Fjanboddez%2Findieblocks`, it should add a Bookmark block with the URL already inserted.

If you're lucky (this seems to depend on whatever notices, etc. are shown), the URL field receives focus, and then on "blur" the block will try to fetch any metadata (i.e., WordPress will kick of a request to the remote URL, which is also why ... I was somewhat paranoid, right). I say lucky because only when (you hit the "Enter" key or) focus is removed from this _field_ does that function get kicked off.

There's nothing that adds, say, selected text to an inner Paragraph block (because I haven't yet figured out how to do such a thing). Also, because a like (the post type) will by default already have a Like block in it, it ... will have two Like blocks if you were to use this thing for likes. (I should figure out how to check for any existing blocks and maybe update those, but ... I again don't know how, yet. Meanwhile, it isn't all that hard to overwrite the block template for the like CPT ...)

**Comment by janboddez** [comment]
Latest main (as of https://github.com/janboddez/indieblocks/commit/72470e7ec09782f3ba7f718811ab11985e18d67b) allows defining a bookmarklets like:

```
javascript:( () => { window.open( 'https://example.org/wp-admin/post-new.php?post_type=indieblocks_like&indieblocks_like_of=' + encodeURIComponent( window.location.href ) + '&indieblocks_selected_text=' + encodeURIComponent( window.getSelection()?.toString().replace( /(?:\r\n|\r|\n)/g, '<br />' ) ) ); } )();
```

Or:
```
javascript:( () => { window.open( 'https://example.org/wp-admin/post-new.php?post_type=indieblocks_note&indieblocks_repost_of=' + encodeURIComponent( window.location.href ) + '&indieblocks_selected_text=' + encodeURIComponent( window.getSelection()?.toString().replace( /(?:\r\n|\r|\n)/g, '<br />' ) ) ); } )();
```

You'll see I'm prefixing everything, that's because I'd like to avoid conflicts. (ActivityPub, for instance, already uses `in_reply_to`.) (Guessing the `toString()` in there is probably superfluous, too.)

I'm also converting newline chars to `<br />` and then do the opposite in my block editor plugin, before I split the thing into separate lines and convert each and everyone of them to a Paragraph block. Can probably be optimized still, but it's better just dumping `urlParams?.get( 'indieblocks_selected_text' )` into a paragraph or freeform block.

I also escape HTML using a built-in WP package (that I hadn't heard of before). Somewhat weirdly, when you call `createBlock( 'core/paragraph', { content: content } )` or something, that content is actually not escaped ... Unlike most things in React or JSX. Is this 100% safe? I don't know. But it's the best I've got right now.

Still super wary/paranoid about XSS or SSRF (because inserting a URL into any of these blocks does or definitely can sorta kick off a server-side request without the user actually having to click "save," which in principle is no different than what happens when they insert a link, but at least then they'd be typing it themselves). Still not 100% comfortable with the idea that anyone could send you a "bookmarky" link with whatever URL/text/HTML they like ...

**Comment by janboddez** [comment]
> Also, because a like (the post type) will by default already have a Like block in it, it ... will have two Like blocks if you were to use this thing for likes.

Solved this one, too. In fact, anything other than the automagically inserted block will be wiped ... Which I think is OK, that's typically what you want in this case.

**Comment by janboddez** [comment]
To do: load script only on supported pages.

**Comment by janboddez** [comment]
Latest `main` comes with an option to explicitly enable bookmarklets support + has example bookmarklets. Both under Settings > IndieBlocks > Miscellaneous, for now. The example bookmarklets don't check what blocks or post types are enabled, they just assume the note CPT for everything but likes (which get a like CPT). I'll (probably) fix that later.

I wanna keep this opt-in because, as mentioned above, while React normally sanitizes "everything," it doesn't sanitize Paragraph blocks' `content`. So someone could, in theory, send or show you a link that would prepopulate a note with some hidden HTML (alongside visible text, for instance). That you might then publish. I've now addressed this by running "selected text" through Gutenberg's built-in `escapeHTML` function, but I may eventually pass text on to the back end and have PHP sanitize it.

**Comment by janboddez** [comment]
Like, once I feel those concerns are adequately addressed, I _might_ remove the "feature flag."

**Comment by janboddez** [comment]
Spun off into https://github.com/janboddez/indieblocks-bookmarklets. _Should_ be compatible even with the current (i.e., "properly" released) version of IndieBlocks. Just install from ZIP and you should be good to go.

I'll remove the functionality from the main plugin.
