### ISSUE TITLE
Move Location panel to Gutenberg

### ISSUE THREAD

**Issue by janboddez** [janboddez/indieblocks#169]
It's typically already in the sidebar, but moving it out of a meta box and into a proper sidebar plugin panel ... For those sites that support it.

Reasoning: while meta boxes are easier to program, the fewer we have of them, the more likely there are none on the Edit Post screen. (Well, it'd depend of course on other plugins.)

**Comment by dshanske** [comment]
Would you be interested in this being added for my plugin as well?

**Comment by janboddez** [comment]
@dshanske You mean Simple Location? I think that should be possible!

Right now IndieBlocks' location function uses either the browser's `navigator.geolocation` or Micropub coordinates (if any) to set a custom field. (It uses a meta box to set (in the `navigator.geolocation` case)/display/edit the value in WP-Admin.) Guessing Simple Location does something similar? (Haven't had a look at it in a while ...)

But I want to eventually move everything over to a "proper" Gutenberg sidebar panel (and keep the old meta box as a fallback).

There's a good chance you could just copy over most of the JavaScript and only have to add or change one or a couple custom field keys. I mean, when I get around to this.

**Comment by dshanske** [comment]
> @dshanske You mean Simple Location? I think that should be possible!
> 
> Right now IndieBlocks' location function uses either the browser's `navigator.geolocation` or Micropub coordinates (if any) to set a custom field. And then I use a meta box to display/edit the value in the back end.
> 
> But I want to eventually move everything over to a "proper" Gutenberg sidebar panel (and keep the old meta box as a fallback).
> 
> There's a good chance you could just copy over most of the JavaScript and only have to add or change one or a couple custom field keys. I mean, when I get around to this.

That's what I was thinking... I'm not much for Gutenberg but unlike some of my other plugins, Simple Location seems like it could easily support both editors and figured I could piggyback on your efforts.

**Comment by janboddez** [comment]
Absolutely!

This isn't the highest prio for me, but it's also relatively easy (I think ...), so I might actually start working on it (like, in a little while).

**Comment by dshanske** [comment]
> Absolutely!
> 
> This isn't the highest prio for me, but it's also relatively easy (I think ...), so I might actually start working on it (like, in a little while).

I've been so busy, I need to get back to a bunch of coding.

**Comment by janboddez** [comment]
Let's think about this for a second.

The lat, lon, and address (actually, it's just a name) fields should display any known data.

If the "update" checkbox is checked and the lat and lon fields are empty (i.e., haven't been saved previously), they should be filled using `navigator.geolocation`.

(If the post is recent --- under an hour is what we've been using --- and both fields are empty, the checkbox should be automatically checked.)

If a post is saved and coordinates where filled out _and_ the box was (still) checked, then the server should store them. If no location name (`geo_address`) was filled out, the server should try and fetch one (well, on the condition that it has an OSM API key).

That's how it's been working so far.

If we were to move this to Gutenberg, we could use its "meta API thingy." Except, then we'd have no control over when exactly the meta is updated (that is, it'll be updated always).

This is probably okay, as long as that "update" checkbox is handled probably. (I.e., nothing will be filled out automatically if it isn't first ticked. And if something was prefilled because it was saved/fetched previously, it'll get resaved [or not?] ... which is just fine.)

The only thing is auto-filling the location "name" that was fetched after after everything is saved a first time. We can use the same trick we used for Share on Mastodon's syndication URL here. Get it from the server after a short delay (and subsequently disable the "update" checkbox).

**Comment by janboddez** [comment]
First attempt: https://github.com/janboddez/indieblocks/commit/dfe12c710885edaf6909ddbd2f3f1c17154f9f9f

Remarks/caveats:
1. The "enable update" toggle is currently true by default. This should be based on post age. Because it may be hard (?) to get the (current) server date in JS to compare to the publish date, we can employ a "trick" and use a "post" object that we fill server side. We can even do the comparison (should it update or not?) server side and give JS access to only a boolean (i.e., the outcome).
2. Other plugins may expose the same metadata in a similar manner, leading to conflicts. I know Jetpack supports the `geo_latitude` and `geo_longitude` custom fields, i.e., uses the same names ... Could provide a fallback just like Share on Mastodon does (provide an option to instead use the "classic" meta box). Or we could start using plugin-specific meta keys ...
3. It doesn't actually auto-fill the fields, yet. I also haven't yet ~~implemented~~ or tested the "background update." Like, the current process for fetching location names won't work ... ~~We have to modify it, make sure it looks at the saved coordinates rather than any `$_POST` variables (which won't be there).~~ Apparently it already works that way :-)

**Comment by janboddez** [comment]
Although I'm not sure `transition_post_status` is the right hook. If it runs twice, the location name will be set the second time.

If it runs once, the location name might not get set at all until the post is updated.

We better run it on `rest_after_insert_{$this->post_type}` (too).

**Comment by janboddez** [comment]
Also, `document.querySelector( '[name="indieblocks_address"]' )` is wrong. Should be, uh, I dunno. Gutenberg/React creates these random IDs, we probably should manually define a class name or something to address this field.

We can probably use `Flex`/`FlexItem` components to horizontally lay out the lat and lon fields.
