### ISSUE TITLE
Can't Disable Notes and Likes

### ISSUE THREAD

**Issue by troutcolor** [janboddez/indieblocks#32]
Hi,
I am trying to disable Notes & Likes, I uncheck the boxes, Save Changes and the boxes are checked again.
I've tried a couple of other checkboxes and seem to be able to enable & disable them.

I am using Version 0.2.0  of the plugin. WordPress 6.0.3 I have quite a few other indieWeb plugins activated.

The only other setting checked in the IndieBlocks plugin is Enable blocks

Cheers

John

**Comment by janboddez** [comment]
I think ... could it be they were enabled in an older version? There was originally only one "post type" setting; I afterward created separate note and like settings, and they will both be enabled if "under the hood" the older setting is, too.

If so, I should probably just delete that value whenever the settings are saved.

What would also work, is have a look in the database, at the `wp_options` table, and delete the row where `option_name` = `indieblocks_settings`. That would reset all settings but should get rid of the issue.

**Comment by troutcolor** [comment]
I did install and use the older version. 
I've deleted the indieblocks_settings row and that sorted it out.
Cheers
John

**Comment by janboddez** [comment]
Great, now I know what to do to fix it for good :-)

**Comment by janboddez** [comment]
23449b50b80e950e4d546ca8f97a467c8507dabd oughta fix that, closing this issue. Release to WP.org repo should happen in a few days.
