### ISSUE TITLE
Like title not shown?

### ISSUE THREAD

**Issue by janboddez** [janboddez/indieblocks#92]
I think, while toying with https://build.boddez.net/likes/, that at one point (I'd converted a note to a like using Post Type Switcher) the title wasn’t shown, even though the setting that enables (i.e., no longer hides) titles for likes, bookmarks, etc. was enabled.

**Comment by jasontucker** [comment]
Yeah I'm running into the same issue on my like page as well as the individual likes.

On the archive page it should show the title above the content
https://jasontucker.blog/likes

And here you can see the title isnt shown in the header
https://jasontucker.blog/likes/2023/05/21/2320394489

The single page for the like is only if someone wants to leave a comment or something I suppose.

**Comment by janboddez** [comment]
> The single page for the like is only if someone wants to leave a comment or something I suppose.

Yeah, and for webmention parsers to pick up.

Have to check what happened still. Can't find anything in the source code that explains this, really.

I also think that on your site, it might be something else.

E.g., I notice that on the notes archive, it does show (autogenerated) titles. You should be able to "hide" these (as they don't add much) using the setting for that. And then enable the "exempt like and bookmark titles" or something.

Interestingly, on your likes archive, titles are in fact given a `screen-reader-text` class. That is something I can't quite explain. :-)

I think what might be happening on you single note and like pages is that maybe there is simply no title block in the template? I don't seem to find the post title, with or without `screen-reader-text` class in those pages' source (but I may have not looked very hard) ...

Also, you _should_ be able to, but this too requires enabling the two "special" like and bookmark title checkboxes on IndieBlocks' Post Type settings page, drop the post content from the like archive template (assuming you've set up a CPT archive template for just likes). What I mean is, with the "right" combination of settings, (at least new) likes should now be able to have an actual title, and have it link to the remote page (there's currently no setting to disable this separately, it's confusing enough as is, but as you said, the like page is really only there for ... for bots, mainly).

Update: might be wise to keep the post content (and thus the microformats) even on the likes archive page, and instead visually hide it (by adding, e.g., a `screen-reader-text` class to it). Webmention parsers won't look at these pages, but "social" readers like Aperture might (although the number of people that use those is, presumably, rather low).
